added CSGO Inventory private check
RumbleFrog/Anti-Private pull request #14
Opened 2019-06-04 19:22 UTC by LemonPAKA

tested in csgo and it works, but didn't test in TF2,DOTA2 and portal2..I think it should work, because I didn't change any code about this part

2019-06-04 23:25 UTC, rumblefrog requested changes
I can't review this PR as all the lines are overwritten, and I can't see what was changed. Can you fix this?

2019-06-05 00:19 UTC, LemonPAKA commented
I think I fixed the overwritten problem...

2019-06-05 02:31 UTC, rumblefrog commented
You should be force pushing the commit to the branch, the indentation changes are unnecessary and makes it harder for me to review.

2019-06-05 02:32 UTC, rumblefrog requested changes

2019-06-05 02:32 UTC, rumblefrog commented on Anti_Private.sp
> +		if(GetEngineVersion()==Engine_CSGO)
Is there a reason why you are duplicating SteamWorks and SteamTools check just for CSGO.

2019-06-05 02:32 UTC, rumblefrog commented on Anti_Private.sp
> +			case Engine_CSGO:
The InventoryURL should be defined on start and engine be checked here

2019-06-05 12:42 UTC, LemonPAKA commented
I don't know how to defined InventoryURL as other games...so I just made a sample for it...and already pushed the commit to the branch

2019-06-08 18:18 UTC, rumblefrog commented
Yeah, I'm not sure why you pushing additional commits to restore and redo. I wanted you to do a **force push** to your branch.

2019-11-05 17:02 UTC, closed without merging